- pom.xml
- src/main/java/com/yongfill/server/global/aspect/LogAOP.java
- src/main/java/com/yongfill/server/global/config/QueryDSLConfig.java
아직 도메인 내부가 안만들어져서 테스트는 못해봤습니다
컨트롤러 추가 후 오류 발생 시 수정하도록 하겠습니다~
> Feat: 로깅 추가

- src/main/java/com/yongfill/server/global/aspect/LogAOP.java
함수 시작 전 로깅하는 부분에서 메서드 매개변수를 안 적었네요
추가했습니다
> FIX: add parameter in log.info

- src/main/java/com/yongfill/server/global/aspect/LogAOP.java
도메인 하위 메서드들이 아닌
server패키지 하위 api에 있는 메서드를 대상으로 필터링 경로를 변경했습니다.
> fix: Change Pointcut Directory

- pom.xml
- src/main/java/com/yongfill/server/ServerApplication.java
- src/main/java/com/yongfill/server/global/aspect/LogAOP.java
1. 메인에서 @EnableAspectJAutoProxy추가
2. 로그에서 리턴값 null일 때 검사하기
> fix: Logging Error

- src/main/java/com/yongfill/server/global/aspect/LogAOP.java
- src/main/resources/log4j2.xml
Logback은 성능상 이슈가 있기 때문에
Sl4j의 로그 구현체를 Log4j2로 교체했습니다.
> feat: Change Log impl Logback to Log4j2

- pom.xml
Sl4j2-log4j2를 위한
log4j-sl4j2-impl 추가
> chore: add dependency to pom.xml

- src/main/java/com/yongfill/server/global/aspect/LogAOP.java
- src/main/resources/log4j2/log4j2.xml
> chore: Change Log Color

- src/main/java/com/yongfill/server/domain/answer/repository/MemberAnswerJpaRepository.java
- src/main/java/com/yongfill/server/domain/comments/repository/CommentJpaRepository.java
- src/main/java/com/yongfill/server/domain/member/repository/MemberJpaRepository.java
- src/main/java/com/yongfill/server/domain/posts/repository/LikeJpaRepository.java
- src/main/java/com/yongfill/server/domain/posts/repository/PostJpaRepository.java
- src/main/java/com/yongfill/server/domain/posts/repository/ViewJpaRepository.java
- src/main/java/com/yongfill/server/domain/question/repository/InterviewQuestionJpaRepository.java
- src/main/java/com/yongfill/server/domain/stack/repository/MemberStackAuthJpaRepository.java
- src/main/java/com/yongfill/server/domain/stack/repository/QuestionStackJpaRepository.java
- src/main/java/com/yongfill/server/domain/vote/repository/CountVoteJpaRepository.java
- src/main/java/com/yongfill/server/domain/vote/repository/MemberQuestionStackVoteJpaRepository.java
모든 Domain에 대한 JPA Repository 생성
> Feat: #4 JPA Repository 생성

- pom.xml
- src/main/java/com/yongfill/server/domain/question/api/InterviewQuestionController.java
- src/main/java/com/yongfill/server/domain/question/dto/InterviewQuestionDto.java
- src/main/java/com/yongfill/server/domain/question/entity/InterviewQuestion.java
- src/main/java/com/yongfill/server/domain/question/repository/InterviewQuestionExpression.java
- src/main/java/com/yongfill/server/domain/question/repository/InterviewQuestionQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/question/service/InterviewQuestionService.java
- src/main/java/com/yongfill/server/domain/stack/entity/QuestionStack.java
- src/main/java/com/yongfill/server/global/common/response/error/ErrorCode.java
- src/test/java/com/yongfill/server/ServerApplicationTests.java
- src/test/java/com/yongfill/server/domain/question/service/InterviewQuestionServiceTest.java
- 문제 (랜덤)조회 API
- 질문 생성 API
- 질문 상태 변경 API
- 질문 삭제 API
- 질문 스택 변경
해당 API 완성
> questions domain 개발 완료

- src/main/java/com/yongfill/server/domain/posts/api/PostAPI.java
- src/main/java/com/yongfill/server/domain/posts/repository/PostJpaRepository.java
- src/main/java/com/yongfill/server/domain/posts/repository/PostQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/posts/repository/PostQueryDSLRepositoryImpl.java
- src/main/java/com/yongfill/server/domain/posts/service/PostService.java
카테고리 이름은 INFO, QNA로 집어넣으시면 됩니다.
카테고리 별로 게시글을 조회하는 기능을 구현했습니다.
```
http://localhost:8080/api/categories/QNA/posts
http://localhost:8080/api/categories/INFO/posts
```
> Feat: 카테고리별 게시글 조회

- src/main/java/com/yongfill/server/domain/member/api/MemberAPI.java
- src/main/java/com/yongfill/server/domain/member/dto/MemberDTO.java
- src/main/java/com/yongfill/server/domain/member/dto/MemberLoginDTO.java
- src/main/java/com/yongfill/server/domain/member/entity/Member.java
- src/main/java/com/yongfill/server/domain/member/repository/MemberJpaRepository.java
- src/main/java/com/yongfill/server/domain/member/service/MemberService.java
- src/main/java/com/yongfill/server/global/common/response/error/ErrorCode.java
- src/main/java/com/yongfill/server/global/exception/CustomException.java
> Feature/member signup signin/#24

- pom.xml
- src/main/java/com/yongfill/server/domain/member/entity/Member.java
- src/main/java/com/yongfill/server/domain/stack/api/MemberStackAuthController.java
- src/main/java/com/yongfill/server/domain/stack/api/QuestionStackController.java
- src/main/java/com/yongfill/server/domain/stack/dto/MemberStackAuthDto.java
- src/main/java/com/yongfill/server/domain/stack/dto/QuestionStackDto.java
- src/main/java/com/yongfill/server/domain/stack/entity/MemberStackAuth.java
- src/main/java/com/yongfill/server/domain/stack/entity/QuestionStack.java
- src/main/java/com/yongfill/server/domain/stack/repository/QuestionStackQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/stack/service/MemberStackAuthService.java
- src/main/java/com/yongfill/server/domain/stack/service/QuestionStackService.java
- src/main/java/com/yongfill/server/global/common/response/error/ErrorCode.java
- src/main/java/com/yongfill/server/global/config/QueryDSLConfig.java
- src/test/java/com/yongfill/server/domain/stack/service/MemberStackAuthServiceTest.java
- src/test/java/com/yongfill/server/domain/stack/service/QuestionStackServiceTest.java
- 스택 조회 API
- 스택 구입 API
- 스택 추가 API
- 스택 수정 API
해당 API 완성
> stack domain 개발 완료

- src/main/java/com/yongfill/server/domain/posts/api/PostAPI.java
- src/main/java/com/yongfill/server/domain/posts/dto/ReadPostDto.java
- src/main/java/com/yongfill/server/domain/posts/service/PostService.java
- src/main/java/com/yongfill/server/domain/posts/service/PostServiceImpl.java
* 역시 CRUD별로 Dto를 분리했습니다.
* 서비스 내 dto, toEntity역할을 하던 메서드의 이름을 dto,toEntity로 통일했습니다.
* 원래 방식은 CreateResponseToDto 이런 식이었는데, 어차피 리턴형식이 다르니까 이름이 toDto로 같아도 다른 함수로 인식됩니다.
```JSON
{
"title": "아 집가고싶다",
"categoryName": "질문게시판",
"content": "솔직히 ㅇㅈ하시는 부분? ㅇㅈ 어 인정~~~",
"writerName": "user1_nick",
"createTime": "2024-07-24T11:07:42.770755",
"lastUpdateTime": "2024-07-24T11:07:42.770755",
"likeCount": 0,
"viewCount": 0,
"updateYn": "N"
}
```
> Feat: 게시글 상세보기

- src/main/java/com/yongfill/server/domain/member/entity/Member.java
- src/main/java/com/yongfill/server/domain/question/dto/InterviewQuestionDto.java
- src/main/java/com/yongfill/server/domain/question/entity/InterviewQuestion.java
- src/main/java/com/yongfill/server/domain/question/repository/InterviewQuestionQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/question/service/InterviewQuestionService.java
- src/main/java/com/yongfill/server/domain/stack/repository/QuestionStackQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/vote/api/MemberQuestionStackVoteController.java
- src/main/java/com/yongfill/server/domain/vote/dto/MemberQuestionStackVoteDto.java
- src/main/java/com/yongfill/server/domain/vote/entity/CountVote.java
- src/main/java/com/yongfill/server/domain/vote/entity/MemberQuestionStackVote.java
- src/main/java/com/yongfill/server/domain/vote/repository/CountVoteQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/vote/repository/MemberQuestionStackVoteQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/vote/service/MemberQuestionStackVoteService.java
- src/main/java/com/yongfill/server/global/common/dto/PageResponseNoEntityDto.java
- src/main/java/com/yongfill/server/global/common/response/error/ErrorCode.java
- src/main/java/com/yongfill/server/global/config/QueryDSLConfig.java
- src/test/java/com/yongfill/server/domain/vote/service/MemberQuestionStackVoteServiceTest.java
- 특정 질문에 대한 투표 API
- 질문 받아오기 API
API 작성 완료
> vote Domain 개발

- src/main/java/com/yongfill/server/domain/question/api/InterviewQuestionController.java
- src/main/java/com/yongfill/server/domain/question/service/InterviewQuestionService.java
- src/test/java/com/yongfill/server/domain/question/service/InterviewQuestionServiceTest.java
> 질문 스택 등록 후 크레딧 지급 API 완성

- src/main/java/com/yongfill/server/domain/posts/api/PostAPI.java
- src/main/java/com/yongfill/server/domain/posts/dto/ReadPostDto.java
- src/main/java/com/yongfill/server/domain/posts/service/PostService.java
- src/main/java/com/yongfill/server/domain/posts/service/PostServiceImpl.java
카테고리 2개 별로 최대 5개씩 게시글의 간소화된 정보를 들고 오는 기능 구현했습니다
> Feat: 메인 페이지에서 게시글 가져오기

- src/main/java/com/yongfill/server/domain/posts/dto/ReadPostDto.java
- src/main/java/com/yongfill/server/domain/posts/repository/LikeJpaRepository.java
- src/main/java/com/yongfill/server/domain/posts/repository/PostQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/posts/service/PostService.java
- src/main/java/com/yongfill/server/domain/posts/service/PostServiceImpl.java
> Feat: 게시글 조회시 좋아요 여부 Dto에 추가

- src/main/java/com/yongfill/server/domain/posts/api/PostAPI.java
- src/main/java/com/yongfill/server/domain/posts/repository/PostQueryDSLRepository.java
- src/main/java/com/yongfill/server/domain/posts/service/PostServiceImpl.java
> Feat: 멤버별 작성글 조회

- src/main/java/com/yongfill/server/domain/answer/api/MemberAnswerApi.java
- src/main/java/com/yongfill/server/domain/answer/dto/MemberAnswerDTO.java
- src/main/java/com/yongfill/server/domain/answer/entity/MemberAnswer.java
- src/main/java/com/yongfill/server/domain/answer/service/MemberAnswerService.java
- src/main/java/com/yongfill/server/domain/question/dto/InterviewQuestionDto.java
- src/main/java/com/yongfill/server/domain/question/entity/InterviewQuestion.java
- src/main/java/com/yongfill/server/domain/question/repository/InterviewQuestionQueryDSLRepository.java
나의 오답노트 조회 api (/api/members/{member_id}/stacks/{stack_id}/answers?page={page}&size={size})를 추가했습니다.
> feat : 나의 오답노트 조회 API 추가

- src/main/java/com/yongfill/server/domain/posts/api/PostAPI.java
- src/main/java/com/yongfill/server/domain/posts/dto/post/ReadPostDto.java
- src/main/java/com/yongfill/server/domain/posts/service/PostServiceImpl.java
POST,DTO의 유저의 프로필 이미지 pathfile도 함께 가져오도록 변경
> Feat: 어드민 api추가, DTO에 파일경로 추가

- src/main/java/com/yongfill/server/global/config/WebConfig.java
> Fix : Edit WebConfig to `@Configuration`

- src/main/java/com/yongfill/server/domain/posts/api/PostAPI.java
> Fix: API 주소 수정

- src/main/java/com/yongfill/server/domain/posts/dto/post/CreatePostDto.java
- src/main/java/com/yongfill/server/domain/posts/dto/post/ReadPostDto.java
- src/main/java/com/yongfill/server/domain/posts/dto/post/UpdatePostDto.java
- src/main/java/com/yongfill/server/domain/posts/entity/Post.java
- src/main/java/com/yongfill/server/domain/posts/service/LikeService.java
- src/main/java/com/yongfill/server/domain/posts/service/PostServiceImpl.java
게시글 수정,생성 시 바로 상세 게시글로 가기 위해 postId를 함께 넘겨줬습니다.
또, 좋아요 취소 시 좋아요 수가 감소 안되는 오류를 해결했습니다
> Feat: 일부 DTO에 postId 추가

- src/main/java/com/yongfill/server/domain/auth/dto/LoginAccessTokenDto.java
로컬 스토리지에 id값을 추가해야해서 DTO추가했습니다
로그아웃기능은 백엔드에서 할 필요가 없다고 느껴 구현 하지 않았습니다.
> Feat: #66 Id DTO 생성

- src/main/java/com/yongfill/server/domain/file/entity/FileEntity.java
> Feat: imageName 속성 추가

- src/main/java/com/yongfill/server/domain/posts/api/PostAPI.java
- src/main/java/com/yongfill/server/domain/posts/dto/post/ReadPostDto.java
- src/main/java/com/yongfill/server/domain/posts/service/PostService.java
포스트 조회 관련 API 로직 수장
post 조회 관련 로직 수정
> feat: #82 Modify post detail API

- src/main/java/com/yongfill/server/domain/answer/api/MemberAnswerApi.java
- src/main/java/com/yongfill/server/domain/answer/service/MemberAnswerService.java
post answer api 로직 수정
answer 등록하는 로직 변경
> feat: #87 Modify post answer api

- src/main/java/com/yongfill/server/domain/posts/entity/Post.java
> 게시글 삭제 시 댓글 함께 삭제

- src/main/java/com/yongfill/server/domain/posts/service/PostService.java
view가 안 올라가던 문제 해결
조회수 안 올라가는 버그 수정
> fix: #90 Fix view

- src/main/java/com/yongfill/server/domain/file/entity/FileEntity.java
- src/main/java/com/yongfill/server/domain/file/entity/FileEntityListener.java
- src/main/java/com/yongfill/server/domain/file/service/FileUploadService.java
Post삭제 시 이미지가 함께 지워지는 동시에 S3에도 지워지도록 수정
> 게시글 삭제 시 S3파일 삭제 연동

- src/main/java/com/yongfill/server/domain/member/entity/Member.java
- src/main/java/com/yongfill/server/domain/member/service/MemberService.java
member가 삭제 안 되던 문제 해결
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
ex) 여기에서 이 부분 잘 모르겠는데 한번 봐주실 수 있나요?
> fix: #98 Fix delete member

- src/main/java/com/yongfill/server/domain/comments/dto/CommentDTO.java
- src/main/java/com/yongfill/server/domain/comments/service/CommentService.java
내가 작성한 댓글 조회 response에 postId를 함께 가져오도록 수정
> Fix : get postId from findCommentsByMember

- src/main/java/com/yongfill/server/ServerApplication.java
- src/main/java/com/yongfill/server/domain/posts/service/ViewService.java
조회수의 정상적인 기록을 위해 매일 0시 0분에 view를 모두 날려버릴 예정입니다
> Feat: View 테이블 삭제 스케줄링

- src/main/java/com/yongfill/server/domain/member/service/MemberService.java
마이페이지 수정시 findNickName -> findID로 변경
> Refactor: #66 수정시 findNickName -> findID로 변경

- src/main/java/com/yongfill/server/domain/member/api/MemberAPI.java
- src/main/java/com/yongfill/server/domain/member/service/MemberService.java
> Feat : credit 추가 api 작성

- src/main/java/com/yongfill/server/domain/question/repository/InterviewQuestionQueryDSLRepository.java
배포 서버의 데이터가 날짜순으로 정렬에 문제가 있다는 점을 확인하였습니다.
따라서 repository의 orderby에서 date 정렬을 제거했습니다.
> Hotfix : memberAnswer 불러오기
